### ISSUE TITLE
Expired certificate prevents download of JASPAR2024 data

### ISSUE THREAD

**Issue by csoneson** [da-bar/JASPAR2024#3]
Hi @da-bar - we recently noticed issues with accessing the `JASPAR2024` data using the Bioconductor package, and the reason appears to be an expired certificate for https://testjaspar.uio.no// where the data is hosted. I believe this is also the reason why `JASPAR2024` currently fails on the Bioconductor devel builders. Is this something that you might be able to address?
Thanks!
Charlotte

**Comment by TeodoraTockovska** [comment]
Hi @da-bar, I have a similar issue and it relates to the expired certificate.

**Comment by da-bar** [comment]
Hi,

Sorry for the delayed reply. It should be fixed now. Thank you for your patience.

**Comment by csoneson** [comment]
Hi @da-bar - thanks a lot for updating the path to the data. A quick question: the Bioconductor annotation packages for release 3.20 were built yesterday, but I noticed that it still seems to contain JASPAR2024 v0.99.6 (which was last updated in October 2023): https://bioconductor.org/checkResults/3.20/data-annotation-LATEST/JASPAR2024/. Also in Bioc devel, I still get v0.99.6. Could there be an issue with the push to Bioc?

**Comment by omsai** [comment]
Still hasn't been pushed to Bioc so as a workaround I'm using the commit ID that fixed the URL in my package `DESCRIPTION`
```
Remotes:
    da-bar/JASPAR2024@ac2f64827a93d058587c66d2cf82c6886031ae96
```

**Comment by csoneson** [comment]
Hi @da-bar, just wanted to quickly check in here again - as far as I can see, Bioconductor still has v0.99.6 of JASPAR2024. Could you check if there was an issue with pushing your latest update upstream? Thanks!

**Comment by da-bar** [comment]
Hi @csoneson , unfortunately it seems that the push didn't make it in time for the current 3.20 Bioconductor release. Sorry for any inconvenience this might have caused.
The version 0.99.7 is available at the Bioconductor development branch:
https://www.bioconductor.org/packages/devel/data/annotation/html/JASPAR2024.html

**Comment by csoneson** [comment]
Thanks @da-bar, that's great - sorry, I missed the devel update! I think you should also be able to update the current release version, by pushing upstream to the RELEASE_3_20 branch.

**Comment by da-bar** [comment]
Hi @csoneson ,

I am not sure I am allowed to push on that branch once it is frozen, but I can check on the Bioconductor mailing list.

**Comment by csoneson** [comment]
Hi @da-bar - the RELEASE_3_20 branch is not frozen (this is the current release), so it should be fine to push to it.

**Comment by omsai** [comment]
@da-bar in support of @csoneson, @lshep from the Bioconductor core team confirmed on the bioc-devel mailing list that you can push the hotfix (see https://stat.ethz.ch/pipermail/bioc-devel/2024-December/020736.html).

**Comment by csoneson** [comment]
Hi @da-bar, happy new year! I just wanted to check in to see if there was any update on getting the `JASPAR2024` fix into Bioc 3.20 - it looks like it's still on v0.99.6. Thanks!

**Comment by csoneson** [comment]
It looks like the certificate for the original server (https://testjaspar.uio.no//) has been renewed, so `JASPAR2024` passes again in Bioc 3.20.
